### ISSUE TITLE
Maybe some error in makefile

### ISSUE THREAD

**Issue by ElderWanng** [yumeng5/JoSH#1]
clone the repo, tryin to reproduce the demo result:
When it comes to run `make` .
Something went wrong:

> `Undefined symbols for architecture x86_64:
>   "_fgetc_unlocked", referenced from:
>       _ReadWord in josh-4268ec.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [josh] Error 1`

**Comment by yumeng5** [comment]
Hi,

I tried to clone the repo on multiple Linux systems and the `make` process never throws any errors and the code runs successfully. Since I am not an expert on makefile-related issues, I unfortunately can't provide any further help on this. Perhaps try running the code on a different system?

Thanks,
Yu
