### ISSUE TITLE
tools folder unavailable 

### ISSUE THREAD

**Issue by nareshr8** [yumeng5/JoSH#2]
Some files in tools folder are used like 
- `tools/tokenizer/lib/*:tools/tokenizer/resources/:tools/tokenizer/build/ Tokenizer` for tokenisation
- `./tools/treetagger/pos_tag.sh` for POS tagging.

I am unable to find the `tools` folder and its folders and sh files. Can u provide which the code or library  you used, so that it would be helpful to replicate the results.

**Comment by yumeng5** [comment]
Hi,

Thanks for trying out the code. I believe you are referring to the preprocessing tool AutoPhrase used in the framework. The AutoPhrase package is included under `preprocess/AutoPhrase.zip` which you need to unzip. You should be able to run the preprocessing code with the unzipped package.

Best,
Yu

**Comment by sharon-gao** [comment]
> Hi,
> 
> Thanks for trying out the code. I believe you are referring to the preprocessing tool AutoPhrase used in the framework. The AutoPhrase package is included under `preprocess/AutoPhrase.zip` which you need to unzip. You should be able to run the preprocessing code with the unzipped package.
> 
> Best,
> Yu

Hi Yu,

Thanks for your development of this tool!

I unziped the `preprocess/AutoPhrase.zip` and run `auto_phrase.sh`. However, there is an error `FileNotFoundError: [Errno 2] No such file or directory: 'AutoPhrase/models/NEW/segmentation.txt'`

It seems that NEW is created in the preprocessing. But I didn't see any file under this folder. Do you have any idea what happened?

Best,
Shuang

**Comment by yumeng5** [comment]
Hi @ShuangNYU,

Thanks for trying out the code. The segmentation results will be written into `preprocess/AutoPhrase/models/NEW` which should be already there after you unzip the `preprocess/AutoPhrase.zip` file. If you accidentally deleted the `NEW` directory (`NEW` directory does not exist), AutoPhrase will instead write the phrase segmented results to `preprocess/AutoPhrase/default_models/NEW` (I'm not sure why AutoPhrase does this, but this is how the AutoPhrase authors implemented it). 

Maybe you could first check if you have a `default_models` directory with `segmentation.model` in it. If so, then you could manually create a `NEW` directory and re-run the code so that everything will be under `NEW` and you should get the correct AutoPhrase results. If not, it would help me to figure out the issue to post your full error trace here.

Thanks,
Yu
